###
GET http://localhost:8080/json/ex01

### ex01 객체 전달 예제
POST http://localhost:8080/json/ex02
Content-Type: application/json

{
"id" : "user",
"password" : "1234"
}

### Response Entity 사용
GET http://localhost:8080/json/ex03

