jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mysql://localhost:3306/scoula_db

# ê¸°ì¡´ ì¬ì©íë jdbc ëë¼ì´ë²
#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql://localhost:3306/scoula_db
jdbc.username=scoula
jdbc.password=1234
