
# ë¡ê·¸ ë¸ë¦¬ê²ì´í° ì¤ì 
log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

# ê¸°ë³¸ ëë¼ì´ë²ë¤ì´ ìëì¼ë¡ ì¤ì¹ëëê²ì ë¹íì±í
log4jdbc.auto.load.popular.drivers=false

# log4jdbcê° ì¬ì©í  ë°ì´í°ë² ì´ì¤ ëë¼ì´ë² ì§ì 
log4jdbc.drivers=com.mysql.cj.jdbc.Driver
